---
- name: Ansible Playbook to Search and Run htop
  hosts: 192.168.122.134  # Replace with your target hosts
  become: yes  # To run tasks that require sudo privilege
  tasks:
    - name: Search for the htop package
      apt:
        update_cache: yes
        name: htop
        state: present
